### ISSUE TITLE
Cannot read properties of undefined (reading 'content')

### ISSUE THREAD

**Issue by noxxxxxxxx** [windicss/vue-cli-plugin-windicss#31]
[test-project.zip](https://github.com/windicss/vue-cli-plugin-windicss/files/7363068/test-project.zip)

Download test.project.zip

```bash
yarn install
yarn serve
```
I use vue-cli create this project and use minimal setting:

<img width="341" alt="simple" src="https://user-images.githubusercontent.com/37919656/137697814-5b96f7df-5812-40e8-bd6e-195386a1884e.png">

If you uncomment `div` style in  `components/HelloWorld.vue` will cause error output:

```css
<style lang="scss">
  body {
    background: #42b983;
    // div {
    //   color: #ddd;
    // }
  }
</style>
```
